"""
Submit jobs to slurm or torque, or with multiprocessing.

============================================================================

        AUTHOR: Michael D Dacre, mike.dacre@gmail.com
  ORGANIZATION: Stanford University
       LICENSE: MIT License, property of Stanford, use as you wish
       CREATED: 2016-44-20 23:03
 Last modified: 2016-04-11 11:25

   DESCRIPTION: Allows simple job submission with either torque, slurm, or
                with the multiprocessing module.
                To set the environement, set QUEUE to one of ['torque',
                'slurm', 'normal'], or run get_cluster_environment().
                To submit a job, run submit().

                All jobs write out a job file before submission, even though
                this is not necessary (or useful) with multiprocessing. In
                normal mode, this is a .cluster file, in slurm is is a
                .cluster.sbatch and a .cluster.script file, in torque it is a
                .cluster.qsub file.

                The name argument is required for submit, it is used to
                generate the STDOUT and STDERR files. Irrespective of mode
                the STDOUT file will be name.cluster.out and the STDERR file
                will be name.cluster.err.

                Note: `.cluster` is added to all names to make deletion less
                dangerous

                Dependency tracking is supported in torque or slurm mode,
                to use it pass a list of job ids to submit or submit_file with
                the `dependencies` keyword argument.

                To clean up cluster files, run clean(directory), if directory
                is not provided, the current directory is used.
                This will delete all files in that were generated by this
                script.

       CAUTION: The clean() function will delete **EVERY** file with
                extensions matching those in this file::
                    .cluster.err
                    .cluster.out
                    .cluster.sbatch & .cluster.script for slurm mode
                    .cluster.qsub for torque mode
                    .cluster for normal mode

============================================================================
"""
##########################
#  Config File Defaults  #
##########################

from .config_file import get_config
DEFAULTS = get_config()

##########################
#  Multiprocessing POOL  #
##########################

POOL = None

#########################
#  Which system to use  #
#########################

# Default is normal, change to 'slurm' or 'torque' as needed.
QUEUE          = 'normal'
ALLOWED_QUEUES = ['torque', 'slurm', 'normal']

###################
#  House Keeping  #
###################

class ClusterError(Exception):

    """A custom exception for cluster errors."""

    pass

#########################################
#  Make our functions easily available  #
#########################################

from .job import Job
from .job import submit
from .job import submit_file
from .job import make_job_file
from .job import clean
from .job import clean_dir

from .queue import Queue
from .queue import check_queue
from .queue import get_cluster_environment

__all__ = ['Job', 'Queue', 'submit', 'submit_file', 'clean', 'make_job_file',
           'check_queue']

##########################
#  Set the cluster type  #
##########################

get_cluster_environment()
check_queue()
